# Generated by Django 5.2.7 on 2025-10-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.hotel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('HOTEL_ADMIN', 'Hotel Admin'), ('STAFF', 'Staff'), ('GUEST', 'Guest')], default='HOTEL_ADMIN', max_length=20),
        ),
    ]
