# Generated by Django 5.2.7 on 2025-10-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='CHECKED_IN', max_length=20)),
                ('check_in_at', models.DateTimeField(auto_now_add=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('running_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelportal.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_room', to='hotelportal.stay'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'number')},
        ),
    ]
