# Generated by Django 5.2.7 on 2025-10-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelportal.room'),
        ),
    ]
