# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0002_alter_stay_room'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('FOOD', 'Food'), ('SERVICE', 'Service')], db_index=True, default='SERVICE', max_length=10)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering within same parent/kind')),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hotelportal.category')),
            ],
            options={
                'ordering': ('position', 'name'),
                'unique_together': {('hotel', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file', models.ImageField(upload_to='item_photos/')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='e.g., plate, item, kg', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotelportal.category')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelportal.imageasset')),
            ],
            options={
                'ordering': ('position', 'name'),
                'indexes': [models.Index(fields=['hotel', 'is_available'], name='hotelportal_hotel_i_09985a_idx'), models.Index(fields=['hotel', 'category', 'is_available'], name='hotelportal_hotel_i_164db1_idx')],
                'unique_together': {('hotel', 'category', 'name')},
            },
        ),
    ]
