# Generated by Django 5.2.7 on 2025-10-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelportal.stay'),
        ),
    ]
