# Generated by Django 5.2.7 on 2025-10-18 13:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0005_alter_cart_stay'),
        ('website', '0002_alter_user_hotel_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FOOD', 'Food'), ('SERVICE', 'Service')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelportal.room')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotelportal.stay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=120)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelportal.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hotelportal.request')),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['hotel', 'status', 'updated_at'], name='hotelportal_hotel_i_f4a549_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['hotel', 'created_at'], name='hotelportal_hotel_i_307d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['hotel', 'kind', 'status'], name='hotelportal_hotel_i_99fd71_idx'),
        ),
        migrations.AddIndex(
            model_name='requestline',
            index=models.Index(fields=['request'], name='hotelportal_request_f22d86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestline',
            unique_together={('request', 'item')},
        ),
    ]
