# Generated by Django 5.2.7 on 2025-10-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelportal', '0006_request_requestline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Only set when kind=SERVICE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='hotelportal.item'),
        ),
    ]
